### PR TITLE
support: load paths from tsconfig.json

### PR DESCRIPTION
**Pull request by zemzheng**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change

support: load paths from tsconfig.json

### CODE REVIEW

**Comment by whxaxes** [comment]
I don't recommend to require `tsconfig-paths` in egg-bin because you still need to import `tsconfig-paths` in your code in prod ( `egg-bin` only works in dev, it may make developer confused that why it works in dev but not in prod. ) .

You can import `tsconfig-paths/register` in `./config/plugin.ts` if you want, it works in both app and agent. 

```typescript
// config/plugin.ts

import 'tsconfig-paths/register';
```

**Comment by zemzheng** [comment]
> I don't recommend to require `tsconfig-paths` in egg-bin because you still need to import `tsconfig-paths` in your code in prod ( `egg-bin` only works in dev, it may make developer confused that why it works in dev but not in prod. ) .
> 
> You can import `tsconfig-paths/register` in `./config/plugin.ts` if you want, it works in both app and agent.
> 
> ```ts
> // config/plugin.ts
> 
> import 'tsconfig-paths/register';
> ```

When we use `npm run tsc` it works as we hope.
And also in vscode it parse tsconfig.json paths as we expected.
But now i need to add  `import 'tsconfig-paths/register';` to config/plugin.ts for only npm run dev/debug?

**Comment by whxaxes** [comment]
@zemzheng `tsc` doesn't transform the path, that's why you need import `tsconfig-paths` in prod, if your code is 

```typescript
import { myFunction } from '@root/myMod';
```

The emitted js is

```js
const myMod_1 = require("@root/myMod");
```

Do you think it still works ?

**Comment by zemzheng** [comment]
> @zemzheng May be you should see this [Microsoft/TypeScript#10866](https://github.com/Microsoft/TypeScript/issues/10866)

Wow, I see. Thank you for your reply.

**Pull request closed without merging**
