### PR TITLE
feat: supports retrieving the port from the configuration file (#250)

### PR DESCRIPTION
**Pull request by JarryChung**
##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message follows commit guidelines

##### Affected core subsystem(s)

- egg-bin

##### Description of change

Adjust the order in which ports are obtained：option `--port` > [_egg.js_ configuration](https://www.eggjs.org/basics/config) `config/config.*.js` > `process.env.EGG_BIN_DEFAULT_PORT` > 7001 > other available ports.

image

closes https://github.com/eggjs/egg-bin/issues/250

### CODE REVIEW

**Comment by JarryChung** [comment]
see issue #250

**Review by fengmk2 — APPROVED** [review]
LGTM

**Comment by fengmk2** [comment]
@JarryChung 单测没通过，需要看看

**Comment by JarryChung** [comment]
@fengmk2 我关注到单测的 demo-app 不是一个标准的 egg 应用，会导致获取配置文件失败，因此我将获取配置文件的逻辑放在  try...catch... 中了，当获取失败时，使用原来的的逻辑。这个处理方式应该要健壮一些，可以避免外部依赖带来的影响。

**Pull request merged**
