### PR TITLE
Pick: "feat(cov): add prerequire option (#53)"

### PR DESCRIPTION
**Pull request by popomore**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change

Pick from a6a2b4a

### CODE REVIEW

**Comment by fengmk2** [comment]
https://github.com/eggjs/egg-mock/blob/a71a58b99e42b4a36148ccfdc23edcb555b07f31/lib/prerequire.js#L8 👍

**Comment by popomore** [comment]
忘记删除 all 了

**Comment by fengmk2** [comment]
好的， @popomore 我接管这个分支，我将 exclude 多余的去掉

**Comment by fengmk2** [comment]
ci pass 后合并

**Comment by popomore** [comment]
我用手机改了代码 :smile:

**Comment by fengmk2** [comment]
@popomore 有点吊

**Comment by popomore** [comment]
+1

**Comment by fengmk2** [comment]
4.0.4

**Pull request merged**
